// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfwmvpvxilosiyewqjtk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmd212cHZ4aWxvc2l5ZXdxanRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTMzNzEsImV4cCI6MjA2NTU4OTM3MX0.gWBahh8riayLE48Xox8HA7tHO2YgelUVw3qT-3xVkcc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);